# Makefile TP 9

all: Exo1 Exo2 Exo3 Exo4

CC=gcc
CFLAGS=-Wall -ansi -g -std=c99

Exo1: Exo1.o
	$(CC) -o Exo1 Exo1.o $(CFLAGS)

Exo2: Exo2.o
	$(CC) -o Exo2 Exo2.o $(CFLAGS)

Exo3: Exo3.o
	$(CC) -o Exo3 Exo3.o $(CFLAGS)

Exo4: Exo4.o
	$(CC) -o Exo4 Exo4.o $(CFLAGS)

clean:
	rm -f *.o
	rm -f *~